### PR TITLE
apps/poll: refactor and fix

### LINKED ISSUE #1150: Poll cannot change order of questions
Poll: after moving a question in the dashboard and saving, the question moves back to it's original position.
NOTE: flip-move lib still working in documents, may require a poll refactor

https://github.com/liqd/adhocracy-plus/issues/1964
https://github.com/liqd/a4-meinberlin/issues/4370

### PR DESCRIPTION
**Pull request by phillimorland**
fixes #1150
fixes https://github.com/liqd/adhocracy-plus/issues/1964
fixes https://github.com/liqd/a4-meinberlin/issues/4370

Notes:
- replaced react-popper with dropdown popper is deprecated and not great ally
- broke up large handle functions as difficult to read, not sure if I did it the best was though
- split up dashbord and detail view, took names from djangoviews, feels simpler this way?

### CODE REVIEW

File: adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx [hunk 1]
```diff
@@ -54,44 +42,59 @@ export const EditPollManagement = (props) => {
...
-  const handleQuestionLabel = (action, params) => {
+  const handleQuestionLabel = (index, label) => {
     const diff = {}
-    const { index, label } = params
     diff[index] = { $merge: { label } }
     setQuestions(update(questions, diff))
   }
 
-  const handleQuestion = (action, params) => {
+  const handleQuestionHelpText = (index, helptext) => {
```
Comment (khamui) [inline adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx:51]: cool! much better

File: adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx [hunk 2]
```diff
@@ -195,7 +194,7 @@ export const EditPollManagement = (props) => {
       onSubmit={(e) => handleSubmit(e)} onChange={() => removeAlert()}
       className="editpoll__questions"
     >
-      <FlipMove easing="cubic-bezier(0.25, 0.5, 0.75, 1)">
+      <FlipMove easing="cubic-bezier(0.25, 0.5, 0.75, 1)" typeName={null}>
```
Comment (khamui) [inline adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx]: `typeName={null}` is this really needed?

File: adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx [hunk 3]
```diff
@@ -104,33 +104,39 @@ export const EditPollManagement = (props) => {
...
-        const otherChoice = getNewChoice('other', true)
-        diff[index] = { choices: { $push: [otherChoice] } }
-      } else {
-        const choiceIndex = questions[index].choices.findIndex(c => c.key === 'other-choice')
-        diff[index] = { choices: { $splice: [[choiceIndex, 1]] } }
-      }
-    } else if (action === 'delete') {
-      const { index, choiceIndex } = params
+    diff[index] = { choices: {} }
+    diff[index].choices[choiceIndex] = { $merge: { label } }
```
Comment (khamui) [inline adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx:110]: more of a general thing: i find these `immutability-helper` functions quite hard to read and to understand. And we do not use them consistently. I think we should either get rid of them entirely, or use them more consistently. What do you think?

**Review by khamui — COMMENTED** [review]
Really good refactors! few comments though.

I didn't test it yet, due to a4 linking problems (try to make it work!). Anyways it would be helpful to get another devs input to this essential refactor :)

File: adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx (hunk 2 above)
Comment (khamui) [reply adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx]: okay, that gets removed in a later commit

Comment (phillimorland) [reply adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx]: missed that when cleaned commits but will leave it if cool?

File: adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx [hunk 4]
```diff
@@ -140,14 +146,17 @@ export const EditPollManagement = (props) => {
   }
 
   const handleSubmit = (e) => {
+    console.log(questions)
```
[the remark this answers is not in the document]
Comment (phillimorland) [reply adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx:149]: yes :p

File: adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx (hunk 3 above)
Comment (phillimorland) [reply adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx:110]: I also don't really like them and I do agree with standardising the usage but i'm not actually sure where else we use them right now?!

**Review by fuzzylogic2000 — APPROVED** [review]
Nice! Great improvement and also works great!
Just merge whenever you have changed what you still wanted to change. :)

File: adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx (hunk 3 above)
Comment (goapunk) [reply adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx:110]: definitely use them in comments as well

File: adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx [hunk 5]
```diff
@@ -0,0 +1,260 @@
...
+import django from 'django'
+import dashboard from '../../../../adhocracy4/dashboard/assets/dashboard'
+import update from 'immutability-helper'
+import { EditPollQuestion } from './EditPollQuestion'
+import { EditPollOpenQuestion } from './EditPollOpenQuestion'
+import Alert from '../../../static/Alert'
+import EditPollDropdown from './EditPollDropdown'
+
+const api = require('adhocracy4').api
+const FlipMove = require('react-flip-move').default
```
Comment (goapunk) [inline adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx:11]: for understanding: why do we use require and not import for the api and flip move?

Comment (phillimorland) [reply adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx:11]: I also wondered this, changing it broke it and so I changed it back intending to investigate after everything was working again but forgot, will take another look when I redo the other stuff

File: adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx [hunk 6]
```diff
@@ -0,0 +1,260 @@
...
+          message: django.gettext('The poll could not be updated.')
+        })
+      })
+  }
+
+  // | Runtime logic and JSX render
+
+  const [questions, setQuestions] = useState([])
+  const [errors, setErrors] = useState([])
+  const [alert, setAlert] = useState(null)
```
Comment (goapunk) [inline adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx:186]: mostly a personal pref but I think those should always be at the very top of the component

File: adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx [hunk 7]
```diff
@@ -0,0 +1,260 @@
...
+
+  useEffect(() => {
+    api.poll.get(props.pollId).done(({ questions }) => {
+      questions.length > 0
+        ? setQuestions(questions)
+        : setQuestions([getNewQuestion()])
+    })
+    // eslint-disable-next-line react-hooks/exhaustive-deps
+  }, [])
```
Comment (goapunk) [inline adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx:195]: similar here, more of a discussion: hooks which run in the background or when one of its dependencies changes should IMO be at the very top (after state stuff but before functions) because otherwise  they are somewhere buried in the lines of a long component and it's harder to understand why the code suddenly executes something. It's good to see such things at the top. What do you guys think?

File: adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx (hunk 5 above)
Comment (goapunk) [reply adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx:11]: I tested it yesterday and `import FlipMove from 'react-flip-move'` works but we need to add react-flip-move to the dev dependencies otherwise the linter will complain. For api `import api from '../.../../static/api' worked as well :)

Comment (phillimorland) [reply adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx:11]: @goapunk thanks figured that, but do you know why it works with require but not import without it being in package.json? I've looked into it and I can't really figure it out?! would be good  need to include so much into a4 dev dependencies!

Comment (goapunk) [reply adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx:11]: Maybe require is not checked by the linter as it kind of executes the required file? And for package.json - if we ever have tests for this component we will have to add it anyway I think?

Comment (goapunk) [reply adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx:11]: just tested and `const test = require('thisDoesntExist')` doesn't trigger a linting error. I don't think that's very good as we won't catch mistakes as easy  like this

File: adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx (hunk 3 above)
Comment (khamui) [reply adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx:110]: will add something, somewhere. But closing this topic here :)

File: adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx (hunk 4 above)
[the remark this answers is not in the document]
Comment (goapunk) [reply adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx:165]: still there :p

**Review by goapunk — APPROVED** [review]
very cool! only the  `console.log()` statements still need to be removed

File: adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx (hunk 4 above)
[the remark this answers is not in the document]
Comment (phillimorland) [reply adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx:165]: fucking rebase

[the remark this answers is not in the document]
Comment (phillimorland) [reply adhocracy4/polls/assets/PollDashboard/EditPollManagement.jsx]: sorry but just added it onto end

**Comment by phillimorland** [comment]
@goapunk @khamui is this good now?

**Review by goapunk — APPROVED** [review]
good from my side, will leave for @khamui to merge
